### ISSUE TITLE
CPD not showing in 'General' Tab.

### ISSUE THREAD

**Issue by swjbakker** [geoffrowland/mahara-artefact_cpds#10]
I have just installed the CPD plugin on 15.04. The plugin seems to work, but is not available on the 'General' tab. Because of this users can not add it to their page and share it with others. Did I miss something? If not, any ideas how to fix this?

**Comment by geoffrowland** [comment]
Hi, have you installed and made visible both the Plugin type: artefact cpds and the Plugin type: blocktype cpd/cpds in the Plugin administration interface?

**Comment by swjbakker** [comment]
No, I only installed the artefact cpds. After installing the other plugin (blocktype) everything works fine. Thanks.

**Comment by geoffrowland** [comment]
Glad it is now working for you. I'll update the documentation to make it more clear.
